// bike_ride-react/src/components/ListStations/index.tsx
import './styles.scss';

import { FC } from 'react';

import useStationsStore from '../../store/useStationsStore/useStationsStore';
import Loading from '../Loading';

const ListStations: FC = () => {
  const {
    isLoadingSt,
    toggleFavorite,
    favorites,
    stationsCount,
    showFavoritesStations,
    isShowFavorites,
  } = useStationsStore();

  if (isLoadingSt) {
    return <Loading />;
  }

  if (!stationsCount && !isShowFavorites) {
    return <p className="listStations_items_notSelected">Станция не выбрана</p>;
  }

  return (
    <div className="listStations">
      <div className="listStations_items">
        {showFavoritesStations().map((station) => (
          <div className="listStations_items_item" key={station.id}>
            <div className="listStations_items_item-title">
              <p>{station.name}</p>
              <div className="listStations_items_item-title-like">
                {favorites.find((i) => i.id === station.id) ? '❤️' : ' '}
              </div>
            </div>
            <p className="listStations_items_item-description">
              Кол-во свободных велосипедов на станции:{' '}
              <span>{station.free_bikes}</span>
            </p>
            <div
              className={`listStations_items_item-button ${favorites.find((i) => i.id === station.id) ? 'del' : ''}`}
              onClick={() => toggleFavorite(station.id)}
            >
              <p>
                {favorites.find((i) => i.id === station.id)
                  ? 'Убрать из избранного'
                  : 'Добавить в избранное'}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ListStations;

// bike_ride-angular/src/app/components/list-stations/list-stations.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { IStationsStore } from 'src/app/models/stations.interfaces';
import { StationsService } from 'src/app/services/stations.service';
import { LoadingComponent } from '../loading/loading.component';

import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzTypographyModule } from 'ng-zorro-antd/typography';
import { IListStationsComponent } from 'src/app/models/ilist-stations-component';

@Component({
  selector: 'app-list-stations',
  standalone: true,
  templateUrl: './list-stations.component.html',
  styleUrl: './list-stations.component.scss',
  imports: [
    CommonModule, 
    LoadingComponent, 
    NzIconModule, 
    NzButtonModule, 
    NzCardModule, 
    NzTypographyModule
  ]
})

export class ListStationsComponent implements IListStationsComponent {
  @Input() stations = {} as IStationsStore;
  @Input() isLoading = false; 
  @Input() isShowFavorites = false;
  @Input() stationsCount = 0;

  constructor(private stationsService: StationsService) {}

  onToggleFavorite(stationId: string) {
    this.stationsService.toggleFavorite(stationId);
  }

  isFavorite(stationId: string): boolean {
    return this.stationsService.favorites.some(f => f.id === stationId);
  }

  showFavoritesStations() {
    return this.stationsService.showFavoritesStations(); 
  }
}
<div *ngIf="isLoading; else listStations" class="loading-container">
  <app-loading />
</div>
<ng-template #listStations>
  <div class="listStations">
    <div class="listStations_items">
      <div *ngIf="!isShowFavorites && !stationsCount"> 
        <h4 nz-typography>Станция не выбрана</h4>
      </div>
      <div
        *ngFor="let station of showFavoritesStations()"
        class="listStations_items_item"
      >
        <nz-card nzTitle="{{ station.name }}">
          <div class="listStations_items_item-like">
            <ng-container *ngIf="isFavorite(station.id)">
              <span nz-icon [nzType]="'star'" [nzTheme]="'fill'"></span>
            </ng-container>
          </div>
          <p>
            Кол-во свободных велосипедов на станции: 
            <span>{{ station.free_bikes }}</span>
          </p>
          <button 
            nz-button 
            nzShape="round" 
            [ngClass]="{ del: isFavorite(station.id) }"
            (click)="onToggleFavorite(station.id)"
          >
            <span 
              nz-icon 
              [nzType]="isFavorite(station.id) ? 'check-circle' : 'star'" 
              [nzTheme]="'fill'">
            </span>
            {{ isFavorite(station.id) ? 'Убрать из избранного' : 'Добавить в избранное' }}
          </button>
        </nz-card>
      </div>
    </div>
  </div>
</ng-template>
